/*
 * Test API
 *
 * Test API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"context"
	"log"
	"net/http"
	"time"

	sw "github.com/cherya/proto-test/internal/app/go"
	client "github.com/cherya/proto-test/pkg/client"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	go func() {
		log.Fatal(http.ListenAndServe(":8080", router))
	}()

	time.Sleep(1 * time.Second)

	c := client.NewAPIClient(client.NewConfiguration())
	lr, r, err := c.DefaultApi.ReadyGet(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	log.Println(lr, r)
	for {
	}
}
