/*
 * Test API
 *
 * Test API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testapi

type ErrorResponse struct {
	Code int32 `json:"code"`

	Status string `json:"status"`

	Error_ string `json:"error"`
}
