/*
 * Test API
 *
 * Test API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package testapi

type ReadyResponse struct {
	Service string `json:"service"`
	Status  string `json:"status"`
}
